spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: '{cipher}AQBLZrnJcNu+LT3TgNfg1HVcxJR0lmgNFO3ceYHR2eE2K+u/er4bh8LTsJNjDUhuo3dLn6dSXh/3nh/AmknnFvXGy9aa4jWXgWd4AdA3Z1PYLBZaUtH0AQKXMJidvF8bkL8OwSpyqS8BM8W9BjksqKdpDZLe0oKbgHgArWT/EhcCOY1b/pgNrzd4oVGyxfCWcduF6RT6KrEyeAJMSkIEpWM4x6R0KTK9TZ7fgs+nBn7Tfq9ejcAhbxuzs5D0j7+aMAeAlNILeLy62nQprPgVGKUnZuG3EjfniE/jarNZ3DfvMANnfbOY1i22YExx81gISbFLWTebSpqkBxGTAjwEdUzLc931J5JVlcRYPTsZeDnfmERJXRZNd7kqKySnrytPJ80='

token:
  expiration_time: 86400000
  secret: '{cipher}AQANB7NicNF0aNWEn0mY2Bl41ItXD5GngE8+eZRCdS83lDAtw3laLHR9Ew8lNmQk9legXtrpqjEaaf9G8rIZdGpWmPricNm5z2lCLWlGZ+wUJwE1d9fceRHXnEr1Mp6eCzuHBXcFJXWmCPJWrwSS9ZxBxInGKx+79GsB9F+u0Spcbpve4W3xHZ1DzTkQnwM1mNUDj/ITjMlwgSKPYC5LdUuDgl6jvP9dHzk480+/IOD7pYDn3QG+8qV5D6MD+pAUiHBZ9OjJWhq6eOKZrcwJC6uDE6gPhr82eFRj3TdlneK6d+ru2GfxbC+0QNdJKD4u8eOSGMgcCQGGYdGyt0n1x8x+qbNjDfK08LnmK19OTZqQ6LIuk3GHCS3S7bKYq+V4af1XpAJoL7Trch2s2LQ02Q1jlXh4+FO0j+2ck00yIbamS+gG1fkYMvyK6UIgY9amShDgPMwr1yV92lC2rdekhNxsykrV/Ozzpz9e86li+5ZMVA=='

gateway:
  ip: 192.168.0.32

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders